# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bijou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=5)),
                ('price', models.IntegerField(max_length=20)),
                ('image_link', models.CharField(max_length=750)),
            ],
        ),
    ]
