# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bijou',
            name='price',
            field=models.IntegerField(),
        ),
    ]
