# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170213_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bijou',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
