# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-12 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170213_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_bijou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('bijouType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bijou')),
            ],
        ),
    ]
