# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sub_bijou'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_bijou',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
